
export const SIZE_DEF = {
    FILE_TITLE_HEIGHT: 20,

    TABLE_MARGIN: {x:30, y:10},
    TABLE_PADDING: 5,
    TABLE_TITLE_HEIGHT: 20,
    TABLE_COLUMN_HEIGHT: 18,

    TABLE_WIDTH: 150,
    INLINE_ELLIPSIS: 15,
};
